### ISSUE TITLE
Safari Bugs

### ISSUE THREAD

**Issue by oguzhantasci** [fatiherikli/fil#2]
Safari bugs.

- code's output is not working. - run button is not working-
- some problem on writing code. -not fluent-

**Comment by oguzhantasci** [comment]
Safari Version 8.0.8 (10600.8.9)

**Comment by o** [comment]
<img width="1317" alt="screen shot 2015-09-14 at 12 27 09" src="https://cloud.githubusercontent.com/assets/179912/9846628/0d4ee686-5adc-11e5-8555-3fec9f1cc508.png">
