### ISSUE TITLE
Python: Why Skulpt?

### ISSUE THREAD

**Issue by amirouche** [fatiherikli/fil#4]
Do you have a particular stance regarding the other solutions to do python in the browser?

**Comment by fatiherikli** [comment]
I tried also brython. I didn't find a proper way to interpret python code without script tags . Skulpt's API is more convenient for running in web-workers.

**Comment by fatiherikli** [comment]
Which one do you suggest? We can still add separate one.

**Comment by amirouche** [comment]
I have my answer :)

Thanks for the good work :+1:
