### ISSUE TITLE
Add JavaScript

### ISSUE THREAD

**Issue by ustun** [fatiherikli/fil#6]
this should be straightforward.

**Comment by fatiherikli** [comment]
I don't want to override console.log :) Do you know any sandboxing solution to do this?

**Comment by fatiherikli** [comment]
Maybe it's possible with self-execution functions. I'll try

**Comment by rusintez** [comment]
+1

**Comment by fatiherikli** [comment]
I just added javascript support. 
https://github.com/fatiherikli/fil/blob/master/workers/javascript.js

**Comment by rusintez** [comment]
:+1:
